"use client";

import { useState } from "react";
import { AlertTriangle, Check, X } from "lucide-react";

interface AIWarningBannerProps {
  /**
   * Whether to show a confirmation checkbox
   * If true, user must check the box to acknowledge the warning
   */
  requireConfirmation?: boolean;
  /**
   * Callback when user confirms/acknowledges
   */
  onConfirm?: (confirmed: boolean) => void;
  /**
   * Compact variant for smaller spaces
   */
  variant?: "default" | "compact";
  /**
   * Custom message (optional)
   */
  customMessage?: string;
}

export default function AIWarningBanner({
  requireConfirmation = false,
  onConfirm,
  variant = "default",
  customMessage,
}: AIWarningBannerProps) {
  const [confirmed, setConfirmed] = useState(false);

  const defaultMessage = "This content has been generated by AI and must be reviewed by you before use. You are responsible for ensuring compliance with all applicable Australian laws and regulations, including but not limited to building codes, safety standards, workplace health and safety requirements, and consumer protection laws.";

  const message = customMessage || defaultMessage;

  const handleCheckboxChange = (checked: boolean) => {
    setConfirmed(checked);
    if (onConfirm) {
      onConfirm(checked);
    }
  };

  if (variant === "compact") {
    return (
      <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg">
        <div className="flex items-start gap-2">
          <AlertTriangle className="w-4 h-4 text-amber-600 mt-0.5 flex-shrink-0" />
          <div className="flex-1">
            <p className="text-xs font-medium text-amber-900 mb-1">
              AI-Generated Content
            </p>
            <p className="text-xs text-amber-800">
              {message}
            </p>
            {requireConfirmation && (
              <label className="flex items-center gap-2 mt-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={confirmed}
                  onChange={(e) => handleCheckboxChange(e.target.checked)}
                  className="w-4 h-4 text-amber-600 border-amber-300 rounded focus:ring-amber-500"
                />
                <span className="text-xs text-amber-900 font-medium">
                  I acknowledge that I have reviewed this AI-generated content and verified its compliance with Australian laws and regulations
                </span>
              </label>
            )}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 bg-amber-50 border-l-4 border-amber-500 rounded-lg">
      <div className="flex items-start gap-3">
        <AlertTriangle className="w-5 h-5 text-amber-600 mt-0.5 flex-shrink-0" />
        <div className="flex-1">
          <h4 className="text-sm font-semibold text-amber-900 mb-2">
            ⚠️ AI-Generated Content Warning
          </h4>
          <p className="text-sm text-amber-800 mb-3">
            {message}
          </p>
          {requireConfirmation && (
            <label className="flex items-start gap-3 cursor-pointer group">
              <input
                type="checkbox"
                checked={confirmed}
                onChange={(e) => handleCheckboxChange(e.target.checked)}
                className="mt-0.5 w-4 h-4 text-amber-600 border-amber-300 rounded focus:ring-amber-500 flex-shrink-0"
              />
              <span className="text-sm text-amber-900 font-medium group-hover:text-amber-950">
                I acknowledge that I have reviewed this AI-generated content and verified its accuracy and compliance with all applicable Australian laws and regulations before use.
              </span>
            </label>
          )}
        </div>
      </div>
    </div>
  );
}

