"use client";

import { useState } from "react";
import { Copy, Check } from "lucide-react";

interface TotalEstimateQuote {
  description?: string;
  totalJobEstimate?: string;
}

interface ParsedQuote {
  totalEstimate?: TotalEstimateQuote;
}

interface CopyForClientButtonProps {
  title: string;
  address?: string;
  summary?: string;
  scopeOfWork?: string;
  inclusions?: string;
  exclusions?: string;
  quoteJson?: string;
}

export default function CopyForClientButton({
  title,
  address,
  summary,
  scopeOfWork,
  inclusions,
  exclusions,
  quoteJson,
}: CopyForClientButtonProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    // Parse quote to get total estimate
    let priceRange = "";
    if (quoteJson) {
      try {
        const quote: ParsedQuote = JSON.parse(quoteJson);
        if (quote.totalEstimate?.totalJobEstimate) {
          priceRange = quote.totalEstimate.totalJobEstimate;
        }
      } catch {
        // Ignore parse errors
      }
    }

    // Build scope of work as numbered list
    const scopeLines = scopeOfWork?.split("\n").filter((line) => line.trim()) || [];
    const numberedScope = scopeLines
      .map((line, i) => `${i + 1}. ${line}`)
      .join("\n");

    // Build inclusions as bullet list
    const inclusionLines = inclusions?.split("\n").filter((line) => line.trim()) || [];
    const bulletInclusions = inclusionLines.map((line) => `• ${line}`).join("\n");

    // Build exclusions as bullet list
    const exclusionLines = exclusions?.split("\n").filter((line) => line.trim()) || [];
    const bulletExclusions = exclusionLines.map((line) => `• ${line}`).join("\n");

    // Build the client-friendly text
    const sections: string[] = [];

    sections.push(`📋 ${title}`);
    
    if (address) {
      sections.push(`📍 ${address}`);
    }

    sections.push(""); // Empty line

    if (summary) {
      sections.push("SUMMARY");
      sections.push(summary);
      sections.push("");
    }

    if (numberedScope) {
      sections.push("SCOPE OF WORK");
      sections.push(numberedScope);
      sections.push("");
    }

    if (bulletInclusions) {
      sections.push("WHAT'S INCLUDED");
      sections.push(bulletInclusions);
      sections.push("");
    }

    if (bulletExclusions) {
      sections.push("NOT INCLUDED");
      sections.push(bulletExclusions);
      sections.push("");
    }

    if (priceRange) {
      sections.push("ESTIMATED PRICE");
      sections.push(priceRange);
      sections.push("");
    }

    sections.push("---");
    sections.push("Generated by OMNEXORA");

    const text = sections.join("\n");

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  return (
    <button
      onClick={handleCopy}
      className="inline-flex items-center px-3 py-1.5 text-sm font-medium rounded-lg bg-amber-500 hover:bg-amber-400 text-slate-900 transition-colors"
    >
      {copied ? (
        <>
          <Check className="w-4 h-4 mr-1.5" />
          <span>Copied!</span>
        </>
      ) : (
        <>
          <Copy className="w-4 h-4 mr-1.5" />
          <span>Copy for Client</span>
        </>
      )}
    </button>
  );
}

