"use client";

import { useState } from "react";
import { X, Copy, Check, Download, Loader2, AlertCircle } from "lucide-react";
import { jsPDF } from "jspdf";

export type JobDocumentType =
  | "SWMS"
  | "VARIATION"
  | "EOT"
  | "PROGRESS_CLAIM"
  | "HANDOVER"
  | "MAINTENANCE";

interface JobDocumentModalProps {
  isOpen: boolean;
  onClose: () => void;
  documentType: JobDocumentType;
  documentTitle: string;
  documentText: string;
  jobId: string;
  jobTitle: string;
  tradeType: string;
  address?: string;
  clientName?: string;
  showWarning?: boolean;
}

const DOCUMENT_LABELS: Record<JobDocumentType, string> = {
  SWMS: "Safe Work Method Statement",
  VARIATION: "Variation / Change Order",
  EOT: "Extension of Time (EOT) Notice",
  PROGRESS_CLAIM: "Progress Claim / Tax Invoice",
  HANDOVER: "Handover & Practical Completion Checklist",
  MAINTENANCE: "Maintenance & Care Guide",
};

const DOCUMENT_FILENAMES: Record<JobDocumentType, string> = {
  SWMS: "swms",
  VARIATION: "variation",
  EOT: "eot",
  PROGRESS_CLAIM: "progress-claim",
  HANDOVER: "handover",
  MAINTENANCE: "maintenance",
};

export default function JobDocumentModal({
  isOpen,
  onClose,
  documentType,
  documentTitle,
  documentText,
  jobId,
  jobTitle,
  tradeType,
  address,
  clientName,
  showWarning = false,
}: JobDocumentModalProps) {
  const [copied, setCopied] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  if (!isOpen) return null;

  const handleCopy = async () => {
    if (!documentText) return;
    try {
      await navigator.clipboard.writeText(documentText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleDownloadPdf = () => {
    if (!documentText) return;
    setIsGeneratingPdf(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;
      let y = margin;

      const checkNewPage = (requiredSpace: number = 20) => {
        if (y + requiredSpace > pageHeight - margin) {
          doc.addPage();
          y = margin;
        }
      };

      const addWrappedText = (text: string, fontSize: number = 11, isBold: boolean = false) => {
        doc.setFontSize(fontSize);
        doc.setFont("helvetica", isBold ? "bold" : "normal");
        const lines = doc.splitTextToSize(text, maxWidth);
        for (const line of lines) {
          checkNewPage();
          doc.text(line, margin, y);
          y += fontSize * 0.4;
        }
        y += 4;
      };

      // Header
      doc.setFillColor(245, 158, 11); // amber-500
      doc.rect(0, 0, pageWidth, 35, "F");

      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      doc.text("OMNEXORA", margin, 18);

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(DOCUMENT_LABELS[documentType], margin, 26);

      y = 50;
      doc.setTextColor(0, 0, 0);

      // Job details
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Job Details", margin, y);
      y += 8;

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      addWrappedText(`Job Title: ${jobTitle}`, 11);
      addWrappedText(`Trade Type: ${tradeType}`, 11);
      if (address) {
        addWrappedText(`Address: ${address}`, 11);
      }
      if (clientName) {
        addWrappedText(`Client: ${clientName}`, 11);
      }
      y += 4;

      // Document content
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      checkNewPage(20);
      doc.text(documentTitle, margin, y);
      y += 10;

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      addWrappedText(documentText, 11);

      // Footer
      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(148, 163, 184);
        doc.text(
          `Generated by OMNEXORA  •  Page ${i} of ${totalPages}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: "center" }
        );
      }

      const filename = `${DOCUMENT_FILENAMES[documentType]}-${jobId.slice(0, 8)}.pdf`;
      doc.save(filename);
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-slate-900/75 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between">
          <div>
            <h2 className="text-xl font-semibold text-slate-900">{documentTitle}</h2>
            <p className="text-sm text-slate-500 mt-1">{DOCUMENT_LABELS[documentType]}</p>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600 transition-colors"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        {/* Warning Banner */}
        {showWarning && (
          <div className="px-6 py-3 bg-amber-50 border-b border-amber-200">
            <div className="flex items-start gap-2">
              <AlertCircle className="w-5 h-5 text-amber-600 mt-0.5 flex-shrink-0" />
              <p className="text-sm text-amber-800">
                ⚠ This job has already been sent to the client. Use Variations, EOTs and new documents to record changes – don&apos;t overwrite the original quote.
              </p>
            </div>
          </div>
        )}

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          <div className="bg-slate-50 rounded-lg p-6 border border-slate-200">
            <pre className="whitespace-pre-wrap font-sans text-sm text-slate-700 leading-relaxed">
              {documentText}
            </pre>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 border-t border-slate-200 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <button
              onClick={handleCopy}
              className="inline-flex items-center px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 font-medium rounded-lg transition-colors text-sm"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 mr-2" />
                  Copied
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 mr-2" />
                  Copy Text
                </>
              )}
            </button>
            <button
              onClick={handleDownloadPdf}
              disabled={isGeneratingPdf}
              className="inline-flex items-center px-4 py-2 bg-amber-500 hover:bg-amber-400 text-slate-900 font-medium rounded-lg transition-colors text-sm disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isGeneratingPdf ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Generating PDF...
                </>
              ) : (
                <>
                  <Download className="w-4 h-4 mr-2" />
                  Download PDF
                </>
              )}
            </button>
          </div>
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 font-medium rounded-lg transition-colors text-sm"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

