"use client";

import { useState } from "react";
import { Loader2, Copy, Check, Download, X } from "lucide-react";
import { jsPDF } from "jspdf";

interface JobDocumentModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  content: string | null;
  jobId: string;
  jobTitle: string;
  tradeType: string;
  address?: string;
  clientName?: string;
  documentType: "SWMS" | "VARIATION" | "EOT" | "PROGRESS_CLAIM" | "HANDOVER" | "MAINTENANCE";
  showWarning?: boolean;
}

const DOCUMENT_LABELS: Record<JobDocumentModalProps["documentType"], string> = {
  SWMS: "Safe Work Method Statement",
  VARIATION: "Variation / Change Order",
  EOT: "Extension of Time Notice",
  PROGRESS_CLAIM: "Progress Claim / Tax Invoice",
  HANDOVER: "Handover & Practical Completion Checklist",
  MAINTENANCE: "Maintenance & Care Guide",
};

export default function JobDocumentModal({
  isOpen,
  onClose,
  title,
  content,
  jobId,
  jobTitle,
  tradeType,
  address,
  clientName,
  documentType,
  showWarning = false,
}: JobDocumentModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleCopy = async () => {
    if (!content) return;
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleDownloadPdf = () => {
    if (!content) return;

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;
      let y = margin;

      // Helper to check and add new page if needed
      const checkNewPage = (requiredSpace: number = 20) => {
        if (y + requiredSpace > pageHeight - margin) {
          doc.addPage();
          y = margin;
        }
      };

      // Helper to add wrapped text
      const addWrappedText = (text: string, fontSize: number = 11, isBold: boolean = false) => {
        doc.setFontSize(fontSize);
        doc.setFont("helvetica", isBold ? "bold" : "normal");
        const lines = doc.splitTextToSize(text, maxWidth);
        for (const line of lines) {
          checkNewPage();
          doc.text(line, margin, y);
          y += fontSize * 0.4;
        }
        y += 4; // Extra spacing after paragraph
      };

      // Header
      doc.setFillColor(245, 158, 11); // amber-500
      doc.rect(0, 0, pageWidth, 35, "F");

      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(255, 255, 255);
      doc.text("OMNEXORA", margin, 18);

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(DOCUMENT_LABELS[documentType], margin, 26);

      y = 50;
      doc.setTextColor(0, 0, 0);

      // Job details
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Job Details", margin, y);
      y += 8;

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      addWrappedText(`Job Title: ${jobTitle}`, 11);
      addWrappedText(`Trade Type: ${tradeType}`, 11);
      if (address) {
        addWrappedText(`Address: ${address}`, 11);
      }
      if (clientName) {
        addWrappedText(`Client: ${clientName}`, 11);
      }
      y += 4;

      // Document content
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      checkNewPage(20);
      doc.text(title, margin, y);
      y += 10;

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      addWrappedText(content, 11);

      // Footer
      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(148, 163, 184); // slate-400
        doc.text(
          `Generated by OMNEXORA  •  Page ${i} of ${totalPages}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: "center" }
        );
      }

      // Save the PDF
      const filename = `${documentType.toLowerCase()}-${jobId.slice(0, 8)}.pdf`;
      doc.save(filename);
    } catch (error) {
      console.error("Error generating PDF:", error);
    }
  };

  return (
    <div className="fixed inset-0 bg-slate-900/75 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between">
          <div>
            <h2 className="text-lg font-semibold text-slate-900">{title}</h2>
            <p className="text-xs text-slate-500 mt-1">{DOCUMENT_LABELS[documentType]}</p>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-600 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Warning Banner */}
        {showWarning && (
          <div className="px-6 py-3 bg-amber-50 border-b border-amber-200">
            <p className="text-sm text-amber-800">
              ⚠️ This job has already been sent to the client. Use Variations, EOTs and new documents to record changes – don&apos;t overwrite the original quote.
            </p>
          </div>
        )}

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {content ? (
            <div className="bg-slate-50 rounded-lg p-6 border border-slate-200">
              <pre className="whitespace-pre-wrap font-sans text-sm text-slate-700 leading-relaxed">
                {content}
              </pre>
            </div>
          ) : (
            <div className="text-center py-12">
              <p className="text-slate-500">No content available</p>
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 border-t border-slate-200 flex items-center justify-between">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 font-medium rounded-lg transition-colors text-sm"
          >
            Close
          </button>
          <div className="flex items-center gap-3">
            {content && (
              <>
                <button
                  onClick={handleCopy}
                  className="inline-flex items-center px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 font-medium rounded-lg transition-colors text-sm"
                >
                  {copied ? (
                    <>
                      <Check className="w-4 h-4 mr-2" />
                      Copied
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4 mr-2" />
                      Copy Text
                    </>
                  )}
                </button>
                <button
                  onClick={handleDownloadPdf}
                  className="inline-flex items-center px-4 py-2 bg-amber-500 hover:bg-amber-400 text-slate-900 font-medium rounded-lg transition-colors text-sm"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download PDF
                </button>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

