"use client";

import { useState } from "react";
import { jsPDF } from "jspdf";
import { Download, Loader2 } from "lucide-react";

interface SwmsPdfButtonProps {
  jobId: string;
  jobTitle: string;
  jobCreatedAt: string;
  tradeType: string;
  propertyType: string;
  address?: string;
  clientName?: string;
  swmsText: string;
}

export default function SwmsPdfButton({
  jobId,
  jobTitle,
  jobCreatedAt,
  tradeType,
  propertyType,
  address,
  clientName,
  swmsText,
}: SwmsPdfButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString("en-AU", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });
  };

  const handleDownloadPdf = () => {
    setIsGenerating(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;
      let y = margin;

      // Helper to check and add new page if needed
      const checkNewPage = (requiredSpace: number = 20) => {
        if (y + requiredSpace > pageHeight - margin) {
          doc.addPage();
          y = margin;
        }
      };

      // Helper to add wrapped text
      const addWrappedText = (text: string, fontSize: number = 11, isBold: boolean = false) => {
        doc.setFontSize(fontSize);
        doc.setFont("helvetica", isBold ? "bold" : "normal");
        const lines = doc.splitTextToSize(text, maxWidth);
        for (const line of lines) {
          checkNewPage();
          doc.text(line, margin, y);
          y += fontSize * 0.4;
        }
        y += 4; // Extra spacing after paragraph
      };

      // Helper to add section heading
      const addSectionHeading = (title: string) => {
        checkNewPage(15);
        y += 8;
        addWrappedText(title, 14, true);
        y += 2;
      };

      // =========================================
      // HEADER
      // =========================================
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("Safe Work Method Statement (SWMS)", pageWidth / 2, y, { align: "center" });
      y += 12;

      // Job details
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      addWrappedText(`Job: ${jobTitle}`, 11);
      addWrappedText(`Trade: ${tradeType}`, 11);
      addWrappedText(`Property Type: ${propertyType}`, 11);
      if (address) {
        addWrappedText(`Location: ${address}`, 11);
      }
      if (clientName) {
        addWrappedText(`Client: ${clientName}`, 11);
      }
      addWrappedText(`Date: ${formatDate(jobCreatedAt)}`, 11);
      y += 8;

      // =========================================
      // SWMS CONTENT
      // =========================================
      // Split SWMS text into sections and format
      const sections = swmsText.split(/\n(?=\d+\.\s+\*\*|##|\*\*)/);
      
      for (const section of sections) {
        const trimmedSection = section.trim();
        if (!trimmedSection) continue;

        // Check if it's a heading (starts with ## or ** or numbered)
        const headingMatch = trimmedSection.match(/^(?:##\s+|\*\*|(\d+\.\s+)\*\*)(.+?)(?:\*\*|$)/);
        if (headingMatch) {
          const headingText = headingMatch[2] || headingMatch[0].replace(/^##\s+|\*\*/g, "").trim();
          addSectionHeading(headingText);
        } else {
          // Regular text content
          // Remove markdown formatting
          let cleanText = trimmedSection
            .replace(/\*\*(.+?)\*\*/g, "$1") // Bold
            .replace(/\*(.+?)\*/g, "$1") // Italic
            .replace(/^[-*]\s+/gm, "• ") // Bullet points
            .replace(/^\d+\.\s+/gm, "") // Numbered lists
            .trim();

          if (cleanText) {
            addWrappedText(cleanText, 11);
          }
        }
      }

      // =========================================
      // FOOTER
      // =========================================
      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(148, 163, 184); // slate-400
        doc.text(
          `Generated by OMNEXORA  •  Page ${i} of ${totalPages}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: "center" }
        );
      }

      // Save the PDF
      const filename = `swms-${jobId.slice(0, 8)}.pdf`;
      doc.save(filename);
    } catch (error) {
      console.error("Error generating SWMS PDF:", error);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      onClick={handleDownloadPdf}
      disabled={isGenerating}
      className="inline-flex items-center px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white font-medium rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed text-sm"
      title="Download SWMS as PDF"
    >
      {isGenerating ? (
        <>
          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
          <span>Generating PDF...</span>
        </>
      ) : (
        <>
          <Download className="w-4 h-4 mr-2" />
          <span>Download SWMS PDF</span>
        </>
      )}
    </button>
  );
}

